# .github/workflows/nightly.yml
name: Nightly builds

on:  
  schedule:
    - cron:  '30 3 * * *'
  push:
    branches:
      - ci*

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  build_webui:
    uses: ./.github/workflows/build.yml
    with:
      variant: webui
